ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.devopsdaws.online
REDIS_HOST: redis-{{ env }}.devopsdaws.online
MYSQL_HOST: mysql-{{ env }}.devopsdaws.online
RABBITMQ_HOST: rabbitmq-{{ env }}.devopsdaws.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devopsdaws.online
USER_HOST: user.backend-alb-{{ env }}.devopsdaws.online
CART_HOST: cart.backend-alb-{{ env }}.devopsdaws.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devopsdaws.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.devopsdaws.online
app_version: v3

# We can also keep this in inventory.ini by [all:vars] (Both are same)
# Usually, we need to provide app_verion specifically for individual components